---
  - name: Install RPM with Satellite certificate
    ansible.builtin.dnf:
      name: "{{ rhsm.cert_rpm }}"
      disable_gpg_check: true
      state: present
    when:
    - rhsm is defined
    - rhsm.cert_rpm is defined
    become: yes
  - name: Register with satellite
    #block:
    #- name: debug vars
    #  debug:
    #    msg: "{{ rhsm }}"
    redhat_subscription:
      state: "{{ rhsm.state }}"
      server_hostname: "{{ rhsm.server_hostname }}"
      activationkey: "{{ rhsm.activationkey }}"
      org_id: "{{ rhsm.org_id }}"
      #auto_attach: "{{ rhsm.auto_attach }}"
      #pool_ids: "{{ rhsm.pool_ids }}"
    when: rhsm is defined
    register: rhsm
    become: yes
  - name: Enable the satellite repo
    community.general.rhsm_repository:
      name: satellite-client-6-for-rhel-8-x86_64-rpms
      state: enabled
    when:
    - rhsm is defined
    become: yes
  - name: Install katello-agent and insights-client
    ansible.builtin.dnf:
      name:
        - katello-agent
        - insights-client
      state: present
    when:
    - rhsm is defined